// src/components/Text/Text.svelte
<script lang="ts">
// biome-ignore-all lint/correctness/noUndeclaredVariables: svelte is partially supported by Biome
type Variants = 'primary' | 'secondary';

export let variant: Variants = 'primary';
const _rest = { ...$$props };

let _textColor = 'base-gray';
if (variant === 'secondary') {
  _textColor = 'lightest-gray';
}
</script>

<p {...rest} class={`font-normal text-base ${textColor}`}>
  <slot />
</p>

<style lang="scss">
  p {
    font-family: "IBM Plex Sans";

    &.base-gray {
      color: var(--c-gray);
    }

    &.lightest-gray {
      color: var(--c-lightest-gray);
    }
  }
</style>

// packages/design-system/src/components/Text/Text.tsx
import { FunctionComponent } from 'preact';
import { cv } from 'css-variants'
import type { TextProps } from './types';

/**
 * Text component
 * 
 * @param props - Text properties
 * @returns Text component
 */
export const Text: FunctionComponent<TextProps> = ({
    variant = 'primary',
    className = '',
    children,
    ...rest
}) => {

    const classNames = cv({
        base: 'font-normal text-base',
        variants: {
            color: {
                primary: 'text-gray',
                secondary: 'text-lightest-gray'
            },
        },
        defaultVariants: {
            color: 'primary',
        }
    })

    return (
        <p
            {...rest}
            class={classNames({ color: variant, className: className })}
            data-variant={variant}
        >
            {children}
        </p>
    );
};
