// apps/web/src/components/H2/H2.svelte
<script lang="ts">
  type Variants = "primary" | "secondary";

  export let variant: Variants = "primary";
  const rest = { ...$$props };

  let textColor: string = "dark-white";
  if (variant === "secondary") {
    textColor = "dark-blue";
  }
</script>

<h2 {...rest} class={`font-medium text-${textColor}`}>
  <slot />
</h2>

<style>
  h2 {
    font-size: 32px;
    line-height: 42px;
    letter-spacing: 1px;
  }
</style>

// packages/design-system/src/components/H2/H2.tsx
import { cv } from 'css-variants';
import { FunctionComponent } from 'preact';
import type { H2Props } from './types';

/**
 * H2 component
 *
 * @param props - H2 properties
 * @returns H2 component
 */
export const H2: FunctionComponent<H2Props> = ({ variant = 'primary', className = '', children, ...rest }) => {
  const classNames = cv({
    base: 'font-ibm-plex-mono text-[32px] leading-[42px] tracking-[1px]',
    variants: {
      color: {
        primary: 'text-white',
        secondary: 'text-dark-blue',
      },
    },
    defaultVariants: {
      color: 'primary',
    },
  });

  return (
    <h2 {...rest} class={classNames({ color: variant, className })}>
      {children}
    </h2>
  );
};
