// apps/web/src/components/H3/H3.svelte
<script lang="ts">
  type Variants = "primary" | "secondary" | "tertiary";

  export let variant: Variants = "primary";
  const rest = { ...$$props };

  let textColor: string = "";
  switch (variant) {
    case "secondary":
      textColor = "dark-blue";
      break;
    case "tertiary":
      textColor = "dark-gray";
      break;
    default:
      textColor = "dark-white";
      break;
  }
</script>

<h3 {...rest} class={`font-medium text-xl text-${textColor}`}>
  <slot />
</h3>

// packages/design-system/src/components/H3/H3.tsx
import { FunctionComponent } from 'preact';
import { cv } from 'css-variants'
import type { H3Props } from './types';

/**
 * H3 component
 * 
 * @param props - H3 properties
 * @returns H3 component
 */
export const H3: FunctionComponent<H3Props> = ({
    variant = 'primary',
    className = '',
    children,
    ...rest
}) => {

    const classNames = cv({
        base: 'font-medium text-xl',
        variants: {
            color: {
                primary: 'text-dark-white',
                secondary: 'text-dark-blue',
                tertiary: 'text-dark-gray'
            },
        },
        defaultVariants: {
            color: 'primary',
        }
    })

    return (
        <h3
            {...rest}
            class={classNames({ color: variant, className })}
        >
            {children}
        </h3>
    );
};
